### ISSUE TITLE
关于压缩包

### ISSUE THREAD

**Issue by MCheping8108** [PangXitong/Minecraft-Communism-Union-Official-Website#2]
压缩包不推荐上传到代码仓库，不方便

**Comment by PangXitong** [comment]
> 压缩包不推荐上传到代码仓库，不方便
这个主要是获取直链下载的链接，然后在进入游戏服务器时自动下载到客户端，百度网盘、天翼网盘等不能直链下载，所以不能应用到Minecraft服务端；压缩包解压之后不能运行，只有".zip"格式压缩包可以被Minecraft Java读取。

**Comment by MCheping8108** [comment]
> > 压缩包不推荐上传到代码仓库，不方便
> 这个主要是获取直链下载的链接，然后在进入游戏服务器时自动下载到客户端，百度网盘、天翼网盘等不能直链下载，所以不能应用到Minecraft服务端；压缩包解压之后不能运行，只有".zip"格式压缩包可以被Minecraft Java读取。
> 

呃，其实我想说的是images.zip 那个

**Comment by PangXitong** [comment]
> > > 压缩包不推荐上传到代码仓库，不方便
> > > 这个主要是获取直链下载的链接，然后在进入游戏服务器时自动下载到客户端，百度网盘、天翼网盘等不能直链下载，所以不能应用到Minecraft服务端；压缩包解压之后不能运行，只有".zip"格式压缩包可以被Minecraft Java读取。
> 
> 呃，其实我想说的是images.zip 那个

好，那我更改一下
